[project]
name = "mcp-on-cloudrun"
version = "0.1.0"
description = "Example of deploying an MCP server on Cloud Run"
requires-python = ">=3.13"
dependencies = [
    "adk>=0.0.5",
    "fastmcp==2.12.4",
    "langchain-community>=0.4.1",
    "locust>=2.43.3",
    "protobuf>=6.33.5",
]
